name: Run Gradle Test

on:
  push:
    branches:
      - main

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Set up JDK
      uses: actions/setup-java@v2
      with:
        distribution: 'adopt'
        java-version: '11'

    - name: Grant execute permission for gradlew
      run: chmod +x ./gradlew

    - name: Run Tests
      run: ./gradlew test

    - name: Archive Serenity Reports
      uses: actions/upload-artifact@v2
      with:
        name: serenity-reports
        path: ///home/runner/work/restful-booker-test/restful-booker-test/build/reports/tests/test/
